apiVersion: v1
kind: Service
metadata:
  name: study-timer-service
spec:
  type: NodePort
  selector:
    app: study-timer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000   # (원하는 포트로 지정, 생략하면 자동 할당)
